var menusJson = {
    "menus": [{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理",
        "menu": [{
            "menuid": 2,
            "icon": "icon-users",
            "menuname": "机构管理",
            "url": "list.jsp",
            "menusid": 3,
            "orCode": "A01"
        }, {
            "menuid": 8,
            "icon": "icon-users",
            "menuname": "用户管理",
            "url": "",
            "menusid": 3,
            "orCode": "A02"
        }, {
            "menuid": 3,
            "icon": "icon-users",
            "menuname": "岗位管理",
            "url": "",
            "menusid": 3,
            "orCode": "A03"
        }, {
            "menuid": 21,
            "icon": "icon-users",
            "menuname": "部门管理",
            "url": "",
            "menusid": 3,
            "orCode": "A04"
        }, {
            "menuid": 22,
            "icon": "icon-users",
            "menuname": "业务管理",
            "url": "",
            "menusid": 3,
            "orCode": "A05"
        }, {
            "menuid": 4,
            "icon": "icon-users",
            "menuname": "权限管理",
            "url": "",
            "menusid": 3,
            "orCode": "A06"
        }, {
            "menuid": 231,
            "icon": "icon-users",
            "menuname": "渠道管理",
            "url": "",
            "menusid": 3,
            "orCode": "A06"
        }],
        "parentOrcode": "A"
    }, {
        "menusid": 1,
        "icon": "icon-sysseting",
        "menusname": "系统配置",
        "menu": [{
            "menuid": 30,
            "icon": "icon-sysseting",
            "menuname": "差错配置",
            "url": "",
            "menusid": 1,
            "orCode": "B05"
        }, {
            "menuid": 14,
            "icon": "icon-sysseting",
            "menuname": "菜单定义",
            "url": "",
            "menusid": 1,
            "orCode": "B07"
        }, {
            "menuid": 12,
            "icon": "icon-sysseting",
            "menuname": "分录定义",
            "url": "",
            "menusid": 1,
            "orCode": "B09"
        }, {
            "menuid": 20,
            "icon": "icon-sysseting",
            "menuname": "公共字典",
            "url": "",
            "menusid": 1,
            "orCode": "B13"
        }, {
            "menuid": 212,
            "icon": "icon-sysseting",
            "menuname": "调账方式配置",
            "url": "",
            "menusid": 1,
            "orCode": "B14"
        }],
        "parentOrcode": "B"
    }, {
        "menusid": 4,
        "icon": "icon-database",
        "menusname": "综合查询",
        "menu": [ {
            "menuid": 292,
            "icon": "icon-database",
            "menuname": "流水查询",
            "url": "",
            "menusid": 4,
            "orCode": "C23"
        }, {
            "menuid": 311,
            "icon": "icon-database",
            "menuname": "对账流水查询",
            "url": "",
            "menusid": 4,
            "orCode": "C24"
        }, {
            "menuid": 312,
            "icon": "icon-database",
            "menuname": "账目查询",
            "url": "",
            "menusid": 4,
            "orCode": "C25"
        }, {
            "menuid": 351,
            "icon": "icon-database",
            "menuname": "无卡支付查询",
            "url": "",
            "menusid": 4,
            "orCode": "C26"
        }],
        "parentOrcode": "C"
    }, {
        "menusid": 2,
        "icon": "icon-work",
        "menusname": "我的任务",
        "menu": [{
            "menuid": 391,
            "icon": "icon-work",
            "menuname": "批量处理",
            "url": "",
            "menusid": 2,
            "orCode": "D06"
        }],
        "parentOrcode": "D"
    }, {
        "menusid": 5,
        "icon": "icon-form",
        "menusname": "统计报表",
        "menu": [{
            "menuid": 111,
            "icon": "icon-form",
            "menuname": "按复核人员统计调账笔数金额",
            "url": "",
            "menusid": 5,
            "orCode": "E04"
        }, {
            "menuid": 29,
            "icon": "icon-form",
            "menuname": "按调账人员统计调账笔数金额",
            "url": "",
            "menusid": 5,
            "orCode": "E04"
        }, {
            "menuid": 211,
            "icon": "icon-form",
            "menuname": "头寸报表",
            "url": "",
            "menusid": 5,
            "orCode": "E05"
        }],
        "parentOrcode": "E"
    }, {
        "menusid": 21,
        "icon": "icon-check",
        "menusname": "对账管理",
        "menu": [{
            "menuid": 31,
            "icon": "icon-check",
            "menuname": "对账操作",
            "url": "",
            "menusid": 21,
            "orCode": "F01"
        }, {
            "menuid": 32,
            "icon": "icon-check",
            "menuname": "文件准备",
            "url": "",
            "menusid": 21,
            "orCode": "F02"
        }],
        "parentOrcode": "F"
    },{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理1",
        "menu": []
    }]
}
