/**
 * Created by rsq0113 on 2018/4/25.
 */
var checkData = [{
    "stateCn": null,
    "progressCn": null,
    "progressNum": null,
    "stlLastDate": null,
    "bussinessCode": null,
    "checkChannel": "UP",
    "checkState": "0",
    "checkProgress": "0",
    "checkStartDate": null,
    "checkStopDate": null,
    "checkDescribe": "银联对账",
    "logLevel": null,
    "stlDate": null,
    "stlDateNext": null,
    "checkUser": "",
    "errorDescribe": null,
    "checkStartStop": null
}, {
    "stateCn": null,
    "progressCn": null,
    "progressNum": null,
    "stlLastDate": null,
    "bussinessCode": null,
    "checkChannel": "DJ",
    "checkState": "0",
    "checkProgress": "0",
    "checkStartDate": null,
    "checkStopDate": null,
    "checkDescribe": "银联数据对账",
    "logLevel": null,
    "stlDate": "",
    "stlDateNext": null,
    "checkUser": "",
    "errorDescribe": null,
    "checkStartStop": null
}, {
    "stateCn": null,
    "progressCn": null,
    "progressNum": null,
    "stlLastDate": null,
    "bussinessCode": null,
    "checkChannel": "AP",
    "checkState": "0",
    "checkProgress": "0",
    "checkStartDate": null,
    "checkStopDate": null,
    "checkDescribe": "支付宝对账",
    "logLevel": null,
    "stlDate": null,
    "stlDateNext": null,
    "checkUser": "",
    "errorDescribe": null,
    "checkStartStop": null
}, {
    "stateCn": null,
    "progressCn": null,
    "progressNum": null,
    "stlLastDate": null,
    "bussinessCode": null,
    "checkChannel": "WP",
    "checkState": "0",
    "checkProgress": "0",
    "checkStartDate": null,
    "checkStopDate": null,
    "checkDescribe": "微信对账",
    "logLevel": null,
    "stlDate": null,
    "stlDateNext": null,
    "checkUser": "",
    "errorDescribe": null,
    "checkStartStop": null
}]
var setDate = {
    "stateCn" : "失败",
    "progressCn" : "对账完毕",
    "progressNum" : "60",
    "stlLastDate" : "20180302",
    "bussinessCode" : null,
    "checkChannel" : "UP",
    "checkState" : "3",
    "checkProgress" : "13",
    "checkStartDate" : "20180423042617",
    "checkStopDate" : null,
    "checkDescribe" : "银联对账",
    "logLevel" : "ERROR",
    "stlDate" : "20180303",
    "stlDateNext" : "20180304",
    "checkUser" : "",
    "errorDescribe" : null,
    "checkStartStop" : null
}

