var menusJson = {
    "menus": [{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理",
        "menu": [{
            "menuid": 2,
            "icon": "icon-users",
            "menuname": "机构管理",
            "url": "/Corc-0/views/account/org/list.jsp",
            "menusid": 3,
            "orCode": "A01"
        }, {
            "menuid": 8,
            "icon": "icon-users",
            "menuname": "用户管理",
            "url": "/Corc-0/views/account/user/list.jsp",
            "menusid": 3,
            "orCode": "A02"
        }, {
            "menuid": 3,
            "icon": "icon-users",
            "menuname": "岗位管理",
            "url": "/Corc-0/views/account/role/list.jsp",
            "menusid": 3,
            "orCode": "A03"
        }, {
            "menuid": 21,
            "icon": "icon-users",
            "menuname": "部门管理",
            "url": "/Corc-0/views/account/department/list.jsp",
            "menusid": 3,
            "orCode": "A04"
        }, {
            "menuid": 22,
            "icon": "icon-users",
            "menuname": "业务管理",
            "url": "/Corc-0/views/account/business/list.jsp",
            "menusid": 3,
            "orCode": "A05"
        }, {
            "menuid": 4,
            "icon": "icon-users",
            "menuname": "权限管理",
            "url": "/Corc-0/views/account/rbac/list.jsp",
            "menusid": 3,
            "orCode": "A06"
        }, {
            "menuid": 231,
            "icon": "icon-users",
            "menuname": "渠道管理",
            "url": "/Corc-0/views/account/ChannelType/list.jsp",
            "menusid": 3,
            "orCode": "A06"
        }],
        "parentOrcode": "A"
    }, {
        "menusid": 1,
        "icon": "icon-sysseting",
        "menusname": "系统配置",
        "menu": [{
            "menuid": 30,
            "icon": "icon-sysseting",
            "menuname": "差错配置",
            "url": "/Corc-0/views/account/ErrTypeMap/list.jsp",
            "menusid": 1,
            "orCode": "B05"
        }, {
            "menuid": 14,
            "icon": "icon-sysseting",
            "menuname": "菜单定义",
            "url": "/Corc-0/views/account/menu/menu.jsp",
            "menusid": 1,
            "orCode": "B07"
        }, {
            "menuid": 12,
            "icon": "icon-sysseting",
            "menuname": "分录定义",
            "url": "/Corc-0/views/account/EntryConfiguration/list.jsp",
            "menusid": 1,
            "orCode": "B09"
        }, {
            "menuid": 20,
            "icon": "icon-sysseting",
            "menuname": "公共字典",
            "url": "/Corc-0/views/account/pubdict/list.jsp",
            "menusid": 1,
            "orCode": "B13"
        }, {
            "menuid": 212,
            "icon": "icon-sysseting",
            "menuname": "调账方式配置",
            "url": "/Corc-0/views/account/ReconMethodConfig/list.jsp",
            "menusid": 1,
            "orCode": "B14"
        }],
        "parentOrcode": "B"
    }, {
        "menusid": 4,
        "icon": "icon-database",
        "menusname": "综合查询",
        "menu": [{
            "menuid": 93,
            "icon": "icon-database",
            "menuname": "本行贷记卡流水查询",
            "url": "/Corc-0/views/account/CoreDjfm/list.jsp",
            "menusid": 4,
            "orCode": "C02"
        }, {
            "menuid": 24,
            "icon": "icon-database",
            "menuname": "银联交易流水查询",
            "url": "/Corc-0/views/account/CupsJnl/list.jsp",
            "menusid": 4,
            "orCode": "C03"
        }, {
            "menuid": 25,
            "icon": "icon-database",
            "menuname": "银联数据来账流水查询",
            "url": "/Corc-0/views/account/CupApeve/list.jsp",
            "menusid": 4,
            "orCode": "C05"
        }, {
            "menuid": 72,
            "icon": "icon-database",
            "menuname": "银联数据往账流水查询",
            "url": "/Corc-0/views/account/CupEveJnl/list.jsp",
            "menusid": 4,
            "orCode": "C05"
        }, {
            "menuid": 51,
            "icon": "icon-database",
            "menuname": "银联头寸数据查询",
            "url": "/Corc-0/views/account/CupsPositionData/list.jsp",
            "menusid": 4,
            "orCode": "C06"
        }, {
            "menuid": 71,
            "icon": "icon-database",
            "menuname": "手续费调账结果",
            "url": "/Corc-0/views/account/errorresults/pgelist.jsp",
            "menusid": 4,
            "orCode": "C06"
        }, {
            "menuid": 73,
            "icon": "icon-database",
            "menuname": "POS数据流水查询",
            "url": "/Corc-0/views/account/CupPos/list.jsp",
            "menusid": 4,
            "orCode": "C07"
        }, {
            "menuid": 91,
            "icon": "icon-database",
            "menuname": "银联交易核心流水查询",
            "url": "/Corc-0/views/account/CoreJnl/list.jsp",
            "menusid": 4,
            "orCode": "C08"
        }, {
            "menuid": 92,
            "icon": "icon-database",
            "menuname": "本代他POS流水查询",
            "url": "/Corc-0/views/account/CoreAifm/list.jsp",
            "menusid": 4,
            "orCode": "C09"
        }, {
            "menuid": 94,
            "icon": "icon-database",
            "menuname": "银联追偿清算流水查询",
            "url": "/Corc-0/views/account/CupsFmc/list.jsp",
            "menusid": 4,
            "orCode": "C11"
        }, {
            "menuid": 95,
            "icon": "icon-database",
            "menuname": "银联往账流水查询",
            "url": "/Corc-0/views/account/CupsErra/list.jsp",
            "menusid": 4,
            "orCode": "C12"
        }, {
            "menuid": 96,
            "icon": "icon-database",
            "menuname": "银联来账流水查询",
            "url": "/Corc-0/views/account/CupsErri/list.jsp",
            "menusid": 4,
            "orCode": "C13"
        }, {
            "menuid": 97,
            "icon": "icon-database",
            "menuname": "银联品牌服务费流水查询",
            "url": "/Corc-0/views/account/CupsBstf/list.jsp",
            "menusid": 4,
            "orCode": "C14"
        }, {
            "menuid": 171,
            "icon": "icon-database",
            "menuname": "银联脱机消费查询",
            "url": "/Corc-0/views/account/CupsOfflineTranc/list.jsp",
            "menusid": 4,
            "orCode": "C14"
        }, {
            "menuid": 172,
            "icon": "icon-database",
            "menuname": "银联发卡周期计费查询",
            "url": "/Corc-0/views/account/CupsIped/list.jsp",
            "menusid": 4,
            "orCode": "C15"
        }, {
            "menuid": 173,
            "icon": "icon-database",
            "menuname": "银联数据发卡周期计费查询",
            "url": "/Corc-0/views/account/CupdataIped/list.jsp",
            "menusid": 4,
            "orCode": "C16"
        }, {
            "menuid": 174,
            "icon": "icon-database",
            "menuname": "银联数据差错交易流水查询",
            "url": "/Corc-0/views/account/CupIerrn/list.jsp",
            "menusid": 4,
            "orCode": "C17"
        }, {
            "menuid": 175,
            "icon": "icon-database",
            "menuname": "银联数据脱机消费查询",
            "url": "/Corc-0/views/account/CupdataOfflineTranc/list.jsp",
            "menusid": 4,
            "orCode": "C18"
        }, {
            "menuid": 176,
            "icon": "icon-database",
            "menuname": "银联数据品牌服务费查询",
            "url": "/Corc-0/views/account/CupdataBstf/list.jsp",
            "menusid": 4,
            "orCode": "C19"
        }, {
            "menuid": 251,
            "icon": "icon-database",
            "menuname": "支付宝流水查询",
            "url": "/Corc-0/views/account/AlipayJnl/list.jsp",
            "menusid": 4,
            "orCode": "C20"
        }, {
            "menuid": 271,
            "icon": "icon-database",
            "menuname": "支付宝核心流水查询",
            "url": "/Corc-0/views/account/CoreAifm1003/list.jsp",
            "menusid": 4,
            "orCode": "C21"
        }, {
            "menuid": 291,
            "icon": "icon-database",
            "menuname": "微信核心流水查询",
            "url": "/Corc-0/views/account/CoreAifm1002/list.jsp",
            "menusid": 4,
            "orCode": "C22"
        }, {
            "menuid": 292,
            "icon": "icon-database",
            "menuname": "微信流水查询",
            "url": "/Corc-0/views/account/Wechatjnl/list.jsp",
            "menusid": 4,
            "orCode": "C23"
        }, {
            "menuid": 311,
            "icon": "icon-database",
            "menuname": "核心ETC对账流水查询",
            "url": "/Corc-0/views/account/CoreEtcJnl/list.jsp",
            "menusid": 4,
            "orCode": "C24"
        }, {
            "menuid": 312,
            "icon": "icon-database",
            "menuname": "ETC对账流水查询",
            "url": "/Corc-0/views/account/Etcjnl/list.jsp",
            "menusid": 4,
            "orCode": "C25"
        }, {
            "menuid": 351,
            "icon": "icon-database",
            "menuname": "无卡支付品牌服务费查询",
            "url": "/Corc-0/views/account/NocpBstf/list.jsp",
            "menusid": 4,
            "orCode": "C26"
        }],
        "parentOrcode": "C"
    }, {
        "menusid": 2,
        "icon": "icon-work",
        "menusname": "我的任务",
        "menu": [{
            "menuid": 391,
            "icon": "icon-work",
            "menuname": "批量处理",
            "url": "/Corc-0/views/account/Plclpzb/list.jsp",
            "menusid": 2,
            "orCode": "D06"
        }],
        "parentOrcode": "D"
    }, {
        "menusid": 5,
        "icon": "icon-form",
        "menusname": "统计报表",
        "menu": [{
            "menuid": 111,
            "icon": "icon-form",
            "menuname": "按复核人员统计调账笔数金额",
            "url": "/Corc-0/views/account/statistical/recomStatList.jsp",
            "menusid": 5,
            "orCode": "E04"
        }, {
            "menuid": 29,
            "icon": "icon-form",
            "menuname": "按调账人员统计调账笔数金额",
            "url": "/Corc-0/views/account/statistical/reconStatList.jsp",
            "menusid": 5,
            "orCode": "E04"
        }, {
            "menuid": 211,
            "icon": "icon-form",
            "menuname": "信用卡头寸报表",
            "url": "/Corc-0/views/account/report303101/list.jsp",
            "menusid": 5,
            "orCode": "E05"
        }, {
            "menuid": 191,
            "icon": "icon-form",
            "menuname": "银联头寸报表",
            "url": "/Corc-0/views/account/report303102/list.jsp",
            "menusid": 5,
            "orCode": "E06"
        }, {
            "menuid": 331,
            "icon": "icon-form",
            "menuname": "微信头寸报表",
            "url": "/Corc-0/views/account/reportWechat/list.jsp",
            "menusid": 5,
            "orCode": "E06"
        }, {
            "menuid": 332,
            "icon": "icon-form",
            "menuname": "支付宝头寸报表",
            "url": "/Corc-0/views/account/reportAlipay/list.jsp",
            "menusid": 5,
            "orCode": "E07"
        }, {
            "menuid": 393,
            "icon": "icon-form",
            "menuname": "微信提现手续费",
            "url": "/Corc-0/views/account/reportWchpd/list.jsp",
            "menusid": 5,
            "orCode": "E07"
        }, {
            "menuid": 333,
            "icon": "icon-form",
            "menuname": "ETC内部账报表",
            "url": "/Corc-0/views/account/reportETC/list.jsp",
            "menusid": 5,
            "orCode": "E08"
        }, {
            "menuid": 352,
            "icon": "icon-form",
            "menuname": "无卡支付头寸报表",
            "url": "/Corc-0/views/account/reportNocpBstf/list.jsp",
            "menusid": 5,
            "orCode": "E09"
        }],
        "parentOrcode": "E"
    }, {
        "menusid": 21,
        "icon": "icon-check",
        "menusname": "对账管理",
        "menu": [{
            "menuid": 31,
            "icon": "icon-check",
            "menuname": "对账操作",
            "url": "/Corc-0/views/accheck/list.html",
            "menusid": 21,
            "orCode": "F01"
        }, {
            "menuid": 32,
            "icon": "icon-check",
            "menuname": "文件准备",
            "url": "/Corc-0/views/checkfile/list.html",
            "menusid": 21,
            "orCode": "F02"
        }],
        "parentOrcode": "F"
    },{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理1",
        "menu": []
    },{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理2",
        "menu": []
    },{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理3",
        "menu": []
    },{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理4",
        "menu": []
    },{
        "menusid": 3,
        "icon": "icon-users",
        "menusname": "用户管理5",
        "menu": []
    }]
}